### ISSUE TITLE
Passing garbage to verify/2 results in an exceptions rather than {:error, ...}

### ISSUE THREAD

**Issue by aselder** [princemaple/elixir-jwt#13]
If I pass random strings to `JWT.verify/2` I get exceptions  rather than an error tuple

`JWT.verify("this_is_a_bad_string", %{key: <my key>})`

gives

```
     ** (Jason.DecodeError) unexpected byte at position 0: 0xB6
     code: |> VerifyAdmin.call(@plug)
     stacktrace:
       (jason) lib/jason.ex:78: Jason.decode!/2
       (yajwt) lib/jwt/jws.ex:84: JWT.Jws.validate_alg/2
       (yajwt) lib/jwt/jws.ex:58: JWT.Jws.verify/3
       (yajwt) lib/jwt.ex:79: JWT.verify/2
       (api_v1_web) lib/api_v1_web/jwt_helper.ex:8: ApiV1Web.JWTHelper.decode/1
       (api_v1_web) lib/api_v1_web/plugs/verify_admin.ex:16: ApiV1Web.Plugs.VerifyAdmin.call/2
       test/api_v1_web/plugs/verify_admin_test.exs:28: (test)
```

Similarly,

`JWT.verify("this is a bad token", %{key: <my key>})`

gives

```
     ** (ArgumentError) non-alphabet digit found: " " (byte 32)
     code: |> VerifyAdmin.call(@plug)
     stacktrace:
       (elixir) lib/base.ex:1002: Base.dec64url/1
       (elixir) lib/base.ex:1018: Base."-do_decode64url/2-lbc$^0/2-0-"/2
       (elixir) lib/base.ex:1012: Base.do_decode64url/2
       (yajwt) lib/jwt/coding.ex:10: JWT.Coding.decode!/2
       (yajwt) lib/jwt/jws.ex:84: JWT.Jws.validate_alg/2
       (yajwt) lib/jwt/jws.ex:58: JWT.Jws.verify/3
       (yajwt) lib/jwt.ex:79: JWT.verify/2
       (api_v1_web) lib/api_v1_web/jwt_helper.ex:8: ApiV1Web.JWTHelper.decode/1
       (api_v1_web) lib/api_v1_web/plugs/verify_admin.ex:16: ApiV1Web.Plugs.VerifyAdmin.call/2
       test/api_v1_web/plugs/verify_admin_test.exs:28: (test)
```

In both cases, these are not valid JWT tokens, but as we all know you get lots of random crap from users, so it would be useful for verify/2 (the non-bang) version to return `{:error, <something>}` rather than crashing.

**Comment by princemaple** [comment]
Thanks for reporting, and the detailed stack trace. I'm currently traveling without a laptop. I will probably get back to this in a week.

Thank you for trying out this little lib with barely any star. If the issue is a blocker for you, you might have to consider switching to other libs like joken. Sorry about the inconvenience.

**Comment by princemaple** [comment]
Hi @aselder I've made a new release. If you are still using this package, please give it a go :)
Otherwise, have fun and thanks for the report!
