### ISSUE TITLE
JWT with "sub" claim cannot be validated without knowing the sub

### ISSUE THREAD

**Issue by norpan** [princemaple/elixir-jwt#3]
When I create a JWT with a `sub` and then try to verify it, I get an error. Surely it should be possible to verify a JWT with a `sub` without having to specify the `sub`?
```
iex(2)> JWT.verify(JWT.sign(%{"sub"=>"user"}, %{key: key}), %{key: key})
{:error, [sub: "user"]}
iex(3)> JWT.verify(JWT.sign(%{"sub"=>"user"}, %{key: key}), %{key: key, sub: "user"})
{:ok, %{"sub" => "user"}}
```

**Comment by princemaple** [comment]
4.1.2.  "sub" (Subject) Claim

   The "sub" (subject) claim identifies the principal that is the
   subject of the JWT.  The claims in a JWT are normally statements
   about the subject.  The subject value MUST **either be scoped to be
   locally unique in the context of the issuer or be globally unique**.
   The processing of this claim is generally application specific.  The
   "sub" value is a case-sensitive string containing a StringOrURI
   value.  Use of this claim is OPTIONAL.

You could issue JWT for different subjects. How could you verify without having to supply a `sub` during verification? Please correct me if I misunderstood the spec. Thanks!

**Comment by princemaple** [comment]
As stated in the README, the implementation was copied from https://github.com/garyf/jwt_claims_ex
I probably got misled by the original implementation.

We can remove the verification then.

**Comment by norpan** [comment]
Well, I'm not sure, but based on the way we use jwts it doesn't work. I've switched over to using Joken instead, which does not have that restriction on `sub`.

**Comment by princemaple** [comment]
Good to know. I was actually wondering why you were using my lib.
