### ISSUE TITLE
No way to control Jason.decode

### ISSUE THREAD

**Issue by dvv** [princemaple/elixir-jwt#42]
Hello!

While having ability to control Jason options here https://github.com/princemaple/elixir-jwt/blob/main/lib/jwt/coding.ex#L14 there is no way to pass them here https://github.com/princemaple/elixir-jwt/blob/main/lib/jwt.ex#L80.

Specifically I would like to pass `keys: :atoms`.

Wonder if you think it worths be present?

TIA

**Comment by princemaple** [comment]
Happy to accept it if you want to send a PR 😉. Pop a `:decode` key out of the verify options and pass it to the decode function.
