### ISSUE TITLE
JWT.InvalidSignatureError from JWT.verify/2

### ISSUE THREAD

**Issue by enkr1** [princemaple/elixir-jwt#50]
I am trying to verify a JWT as a verifier, but followed the solution given [here](https://github.com/princemaple/elixir-jwt/issues/6#issuecomment-468029264) I still couldn't make it work.

My codes:
```elixir
jwt = "eyJh....."
pem = JWT.Algorithm.RsaUtil.public_key(".", "public.pem")
IO.inspect(pem, label: "pem")
JWT.verify(jwt, %{
  alg: "RS256",
  key: pem
})

```

output: 
```elixir
pem: [65537,
237435391219...2230143]
{:error, JWT.InvalidSignatureError}
```

___

> I am sure that my `public.pem` & `jwt` are valid.

**Comment by princemaple** [comment]
Any documentation about how it was signed?

Any chance you can share the public key? And the jwt?

**Comment by princemaple** [comment]
Ping. Probably missed my comment.

**Comment by enkr1** [comment]
Hi @princemaple, 

I am so sorry for the inconvenience, after talking with the team. We realised that the issue was the test token was expired. 

> Was totally misled by the error message ...

**Comment by princemaple** [comment]
Thanks for getting back to me! Have a good day. ref #6
