### ISSUE TITLE
Error on RSA JWT token verification

### ISSUE THREAD

**Issue by knightq** [princemaple/elixir-jwt#6]
Given
```elixir
token = "eyJhbGciOiJSUzI1NiIsImtpZCI6bnVsbH0.eyJpc3MiOiJlcGVyc29uYW0uY29tIiwic3ViIjoyNTQyLCJhdmEiOiIvL2VwZXJzb25hbS5zMy5ldS13ZXN0LTEuYW1hem9uYXdzLmNvbS91c2Vycy9hdmF0YXJzLzAwMC8wMDIvODU0L29yaWdpbmFsL1NjaGVybWF0YSAyMDE4LTA5LTA2IGFsbGUgMTYuMTQuNDgucG5nIiwiZm5hIjoiU2FsaWNldHRpIiwidW5hIjoia25pZ2h0cSIsImV4cCI6MTU1MTMxMTkxMSwianRpIjoiZTkyMTc0M2QtM2JjMy00N2U5LWI0ZDctNTMwNmNiNGI1ZmIwIn0.ukB_tFxBVQe2bx-3cbaPPwahPGdCydERsg_RWwxtPuJ4NYEW-z0o5-A4zFw9Ur8Ow6kx8RAUgtIQmBrNznaVgd4hKWhfySG8nbLAtdUYDMYghV9ZJO8u3sskjvMzil-9BpDtUj2zYxcjleLeGIxaJGDnfq88THGyiJ9hWvCQDIk6A6VzjQEzRI0svYvLxcpZthU1BHCLW2JOIHs-4_pqUOUXiVF9x5JZN2OirCogr7sI8UEkp9XDIaTzg6nEnfGbBqAHOGlijSW06BumNWa2-ilMP9z-tMVukuzB1wpVmftEaZV6qvBeYg4ISJ3q6dkEafgm9xHSbvVtU6RLhm2klQ"
opts = %{
  alg: "RS256",
  key: "-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8bp237rLGKRm0+2ZirUj
hNCtL/ZyHrINaXLBbDsz4eiw6imyEIQs1iFecAO5mGR/LxtNyHobyfHGipDFrIif
PKEsG7pfupJwpMpbnpc2m6k4WN56J2zCMzCClkR5EJ4OQJr0g5QDp1moA5OMfHg4
6ZCLqrrmJcz8kGX0jD54ElKEjWP9iw/BRYEJSHMyr9TCBAYoZVWetfrOqsbqtPPu
sM8v5NmsdrTBJeJhSZ0EQJ55+wzUdTCAaYIB1nr9nR0YBFETYc3FRFqabjY4rFam
qS4F9kwt/MbtAxaoTUOG7tf9Ci92z87rPz85O0aHkfnwvr3I8B1od6qq9DZPeDWZ
UwIDAQAB
-----END PUBLIC KEY-----
"
}
JWT.verify(token, opts)
```

I get this error:

** (FunctionClauseError) no function clause matching in JWT.Algorithm.Rsa.modulus/1

    The following arguments were given to JWT.Algorithm.Rsa.modulus/1:

        # 1
        "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8bp237rLGKRm0+2ZirUj\nhNCtL/ZyHrINaXLBbDsz4eiw6imyEIQs1iFecAO5mGR/LxtNyHobyfHGipDFrIif\nPKEsG7pfupJwpMpbnpc2m6k4WN56J2zCMzCClkR5EJ4OQJr0g5QDp1moA5OMfHg4\n6ZCLqrrmJcz8kGX0jD54ElKEjWP9iw/BRYEJSHMyr9TCBAYoZVWetfrOqsbqtPPu\nsM8v5NmsdrTBJeJhSZ0EQJ55+wzUdTCAaYIB1nr9nR0YBFETYc3FRFqabjY4rFam\nqS4F9kwt/MbtAxaoTUOG7tf9Ci92z87rPz85O0aHkfnwvr3I8B1od6qq9DZPeDWZ\nUwIDAQAB\n-----END PUBLIC KEY-----\n"

    Attempted function clauses (showing 1 out of 1):

        def modulus([_e, n | _d])

    (yajwt) lib/jwt/algorithm/rsa.ex:45: JWT.Algorithm.Rsa.modulus/1
    (yajwt) lib/jwt/algorithm/rsa.ex:49: JWT.Algorithm.Rsa.validate_key_size!/1
    (yajwt) lib/jwt/algorithm/rsa.ex:40: JWT.Algorithm.Rsa.verify?/4
    (yajwt) lib/jwt/jws.ex:95: JWT.Jws.verify_signature/3
    (yajwt) lib/jwt/jws.ex:59: JWT.Jws.verify/3
    (yajwt) lib/jwt.ex:79: JWT.verify/2

**Comment by princemaple** [comment]
Hi @knightq RSA keys should be loaded by the util function before being passed in as config.

```elixir
private_key = JWT.Algorithm.RsaUtil.private_key("path/to/", "key.pem")
opts = %{
  alg: "RS256",
  key: private_key
}
```

**Comment by enkr1** [comment]
> ```elixir
> 
> ```

Hi @princemaple,

I have tried your suggestion but it didn't work, this is my output: 
```elixir
{:error, JWT.InvalidSignatureError}
```

My code: 
```elixir
pem = JWT.Algorithm.RsaUtil.public_key(".", "public.pem") 
IO.inspect(pem, label: "pem after")
JWT.verify(jwt, %{
  alg: "RS256",
  key: pem
})
```

**Comment by princemaple** [comment]
You'd normally encode with public key and verify with private key. Your code seems to be using the public key. Try the private key?

**Comment by enkr1** [comment]
> You'd normally encode with public key and verify with private key. Your code seems to be using the public key. Try the private key?

Hi @princemaple thanks for taking the time to reply!


Let me just briefly explain what am i doing: 
I am trying to verify a JWT while I am given only the PK of the sender. From my understanding, I should be able to verify the JWT by using the public key generated by the sender who has the secret key, am i right?

**Comment by princemaple** [comment]
Yes. This way should work as well. I was thinking maybe you used the same key to encode and verify - apparently not the case.

I don't want to trigger more notifications for the OP. Can you file a new issue with more details?
